//! The real store.
//!
//! Postgres, per decision HLIN-A-0006. Queries are written out rather than
//! generated by `sqlx`'s macros, deliberately: the macros check queries against
//! a live database at *compile* time, which would make a database necessary to
//! build the shell at all. Migrations still use `sqlx`, embedded with
//! [`sqlx::migrate!`], which reads a directory at compile time and needs no
//! connection.
//!
//! Every operation on a layout is one statement or one transaction. A layout
//! and its panels are edited as one thing, so writing them separately would
//! leave a window where a surface has yesterday's panels and today's settings.

use async_trait::async_trait;
use chrono::Utc;
use sqlx::Row;
use sqlx::postgres::{PgPool, PgPoolOptions, PgRow};
use uuid::Uuid;

use super::types::{
    Layout, NewLayout, PanelInstance, PendingLogin, PlatformSnapshot, Session, Violation,
    Visibility,
};
use super::{Result, Store, StoreError};

/// The migrations, embedded at compile time from `crates/hlin/migrations`.
pub static MIGRATIONS: sqlx::migrate::Migrator = sqlx::migrate!("./migrations");

/// The shell's Postgres-backed store.
#[derive(Debug, Clone)]
pub struct PostgresStore {
    pool: PgPool,
}

impl PostgresStore {
    /// Connect, and bring the schema up to date.
    ///
    /// Migrations run on connect rather than as a separate deployment step, so
    /// a shell that starts is a shell whose schema matches its code. With more
    /// than one instance, Postgres advisory locks inside `sqlx` mean only one
    /// migrates and the rest wait.
    pub async fn connect(database_url: &str) -> Result<Self> {
        let pool = PgPoolOptions::new()
            .max_connections(16)
            .connect(database_url)
            .await
            .map_err(|error| StoreError::Unavailable(error.to_string()))?;

        MIGRATIONS
            .run(&pool)
            .await
            .map_err(|error| StoreError::Unavailable(format!("migrations failed: {error}")))?;

        Ok(Self { pool })
    }

    /// Wrap an existing pool, without migrating.
    pub fn from_pool(pool: PgPool) -> Self {
        Self { pool }
    }

    /// The underlying pool, for tests and for the shell's health check.
    pub fn pool(&self) -> &PgPool {
        &self.pool
    }
}

fn unavailable(error: sqlx::Error) -> StoreError {
    StoreError::Unavailable(error.to_string())
}

fn snapshot_from_row(row: &PgRow) -> Result<PlatformSnapshot> {
    Ok(PlatformSnapshot {
        platform_id: row.try_get("platform_id").map_err(unavailable)?,
        manifest: row.try_get("manifest").map_err(unavailable)?,
        contract_hash: row.try_get("contract_hash").map_err(unavailable)?,
        contract_version: row.try_get("contract_version").map_err(unavailable)?,
        observed_at: row.try_get("observed_at").map_err(unavailable)?,
        consecutive_observations: row
            .try_get("consecutive_observations")
            .map_err(unavailable)?,
        // A column added after the fact, and read leniently: a row written
        // before the migration has SQL NULL here, and a shell that refused to
        // read its own history over a platform that has never misbehaved would
        // be a poor trade.
        last_violation: row
            .try_get::<Option<serde_json::Value>, _>("last_violation")
            .ok()
            .flatten()
            .and_then(|value| serde_json::from_value(value).ok()),
    })
}

fn layout_from_row(row: &PgRow, panels: Vec<PanelInstance>) -> Result<Layout> {
    let visibility: String = row.try_get("visibility").map_err(unavailable)?;
    let visibility = Visibility::parse(&visibility).ok_or_else(|| {
        StoreError::Corrupt(format!(
            "`{visibility}` is not a visibility this shell knows"
        ))
    })?;

    Ok(Layout {
        id: row.try_get("id").map_err(unavailable)?,
        owner: row.try_get("owner").map_err(unavailable)?,
        title: row.try_get("title").map_err(unavailable)?,
        visibility,
        forked_from: row.try_get("forked_from").map_err(unavailable)?,
        time_range: row.try_get("time_range").map_err(unavailable)?,
        panels,
        created_at: row.try_get("created_at").map_err(unavailable)?,
        updated_at: row.try_get("updated_at").map_err(unavailable)?,
    })
}

fn panel_from_row(row: &PgRow) -> Result<PanelInstance> {
    Ok(PanelInstance {
        id: row.try_get("id").map_err(unavailable)?,
        platform_id: row.try_get("platform_id").map_err(unavailable)?,
        panel_key: row.try_get("panel_key").map_err(unavailable)?,
        kind_override: row.try_get("kind_override").map_err(unavailable)?,
        title_override: row.try_get("title_override").map_err(unavailable)?,
        selections: row.try_get("selections").map_err(unavailable)?,
        customizations: row.try_get("customizations").map_err(unavailable)?,
        position: row.try_get("position").map_err(unavailable)?,
        created_at: row.try_get("created_at").map_err(unavailable)?,
    })
}

const LAYOUT_COLUMNS: &str =
    "id, owner, title, visibility, forked_from, time_range, created_at, updated_at";

const PANEL_COLUMNS: &str = "id, platform_id, panel_key, kind_override, title_override, \
     selections, customizations, position, created_at";

impl PostgresStore {
    async fn panels_for(&self, layout_id: Uuid) -> Result<Vec<PanelInstance>> {
        let query = format!(
            "SELECT {PANEL_COLUMNS} FROM panel_instances WHERE layout_id = $1 ORDER BY created_at, id"
        );
        let rows = sqlx::query(&query)
            .bind(layout_id)
            .fetch_all(&self.pool)
            .await
            .map_err(unavailable)?;
        rows.iter().map(panel_from_row).collect()
    }

    async fn hydrate(&self, rows: Vec<PgRow>) -> Result<Vec<Layout>> {
        let mut layouts = Vec::with_capacity(rows.len());
        for row in rows {
            let id: Uuid = row.try_get("id").map_err(unavailable)?;
            let panels = self.panels_for(id).await?;
            layouts.push(layout_from_row(&row, panels)?);
        }
        Ok(layouts)
    }
}

#[async_trait]
impl Store for PostgresStore {
    async fn platform_snapshot(&self, platform_id: &str) -> Result<Option<PlatformSnapshot>> {
        let row = sqlx::query(
            "SELECT platform_id, manifest, contract_hash, contract_version, observed_at, \
             consecutive_observations, last_violation FROM platforms WHERE platform_id = $1",
        )
        .bind(platform_id)
        .fetch_optional(&self.pool)
        .await
        .map_err(unavailable)?;

        row.as_ref().map(snapshot_from_row).transpose()
    }

    async fn platform_snapshots(&self) -> Result<Vec<PlatformSnapshot>> {
        let rows = sqlx::query(
            "SELECT platform_id, manifest, contract_hash, contract_version, observed_at, \
             consecutive_observations, last_violation FROM platforms ORDER BY platform_id",
        )
        .fetch_all(&self.pool)
        .await
        .map_err(unavailable)?;

        rows.iter().map(snapshot_from_row).collect()
    }

    async fn observe_platform(&self, snapshot: PlatformSnapshot) -> Result<PlatformSnapshot> {
        // The count carries forward only while the hash is unchanged, which is
        // the whole of the debounce the registry relies on. Doing it in the
        // statement rather than read-then-write means two shell instances
        // polling the same platform cannot lose an observation between them.
        let row = sqlx::query(
            "INSERT INTO platforms (platform_id, manifest, contract_hash, contract_version, \
                                    observed_at, consecutive_observations)
             VALUES ($1, $2, $3, $4, $5, 1)
             ON CONFLICT (platform_id) DO UPDATE SET
                 manifest = EXCLUDED.manifest,
                 contract_hash = EXCLUDED.contract_hash,
                 contract_version = EXCLUDED.contract_version,
                 observed_at = EXCLUDED.observed_at,
                 consecutive_observations = CASE
                     WHEN platforms.contract_hash = EXCLUDED.contract_hash
                     THEN platforms.consecutive_observations + 1
                     ELSE 1
                 END
             RETURNING platform_id, manifest, contract_hash, contract_version, observed_at, \
                       consecutive_observations, last_violation",
        )
        .bind(&snapshot.platform_id)
        .bind(&snapshot.manifest)
        .bind(&snapshot.contract_hash)
        .bind(&snapshot.contract_version)
        .bind(snapshot.observed_at)
        .fetch_one(&self.pool)
        .await
        .map_err(unavailable)?;

        snapshot_from_row(&row)
    }

    async fn record_violation(
        &self,
        platform_id: &str,
        declared: &str,
        expected_major: u64,
        changes: Vec<String>,
    ) -> Result<Violation> {
        // The count is read and incremented inside the statement, for the same
        // reason `observe_platform` does: two shell instances watching one
        // platform must not lose a violation between them.
        let existing: Option<serde_json::Value> =
            sqlx::query("SELECT last_violation FROM platforms WHERE platform_id = $1")
                .bind(platform_id)
                .fetch_optional(&self.pool)
                .await
                .map_err(unavailable)?
                .and_then(|row| row.try_get("last_violation").ok())
                .flatten();

        let seen = existing
            .and_then(|value| serde_json::from_value::<Violation>(value).ok())
            .map(|previous| previous.seen)
            .unwrap_or(0);

        let violation = Violation {
            declared: declared.to_string(),
            expected_major,
            changes,
            at: Utc::now(),
            seen: seen + 1,
        };

        let encoded = serde_json::to_value(&violation)
            .map_err(|error| StoreError::Unavailable(error.to_string()))?;

        sqlx::query("UPDATE platforms SET last_violation = $2 WHERE platform_id = $1")
            .bind(platform_id)
            .bind(&encoded)
            .execute(&self.pool)
            .await
            .map_err(unavailable)?;

        Ok(violation)
    }

    async fn forget_platform(&self, platform_id: &str) -> Result<bool> {
        let done = sqlx::query("DELETE FROM platforms WHERE platform_id = $1")
            .bind(platform_id)
            .execute(&self.pool)
            .await
            .map_err(unavailable)?;
        Ok(done.rows_affected() > 0)
    }

    async fn layout(&self, id: Uuid) -> Result<Option<Layout>> {
        let query = format!("SELECT {LAYOUT_COLUMNS} FROM layouts WHERE id = $1");
        let row = sqlx::query(&query)
            .bind(id)
            .fetch_optional(&self.pool)
            .await
            .map_err(unavailable)?;

        match row {
            Some(row) => {
                let panels = self.panels_for(id).await?;
                Ok(Some(layout_from_row(&row, panels)?))
            }
            None => Ok(None),
        }
    }

    async fn layouts_owned_by(&self, owner: &str) -> Result<Vec<Layout>> {
        let query = format!(
            "SELECT {LAYOUT_COLUMNS} FROM layouts WHERE owner = $1 ORDER BY updated_at DESC"
        );
        let rows = sqlx::query(&query)
            .bind(owner)
            .fetch_all(&self.pool)
            .await
            .map_err(unavailable)?;
        self.hydrate(rows).await
    }

    async fn published_layouts(&self) -> Result<Vec<Layout>> {
        let query = format!(
            "SELECT {LAYOUT_COLUMNS} FROM layouts WHERE visibility = 'published' \
             ORDER BY updated_at DESC"
        );
        let rows = sqlx::query(&query)
            .fetch_all(&self.pool)
            .await
            .map_err(unavailable)?;
        self.hydrate(rows).await
    }

    async fn create_layout(&self, new: NewLayout) -> Result<Layout> {
        let id = Uuid::new_v4();
        let now = Utc::now();

        let mut transaction = self.pool.begin().await.map_err(unavailable)?;

        sqlx::query(
            "INSERT INTO layouts (id, owner, title, visibility, forked_from, time_range, \
                                  created_at, updated_at)
             VALUES ($1, $2, $3, $4, $5, $6, $7, $7)",
        )
        .bind(id)
        .bind(&new.owner)
        .bind(&new.title)
        .bind(new.visibility.as_str())
        .bind(new.forked_from)
        .bind(&new.time_range)
        .bind(now)
        .execute(&mut *transaction)
        .await
        .map_err(unavailable)?;

        for panel in &new.panels {
            insert_panel(&mut transaction, id, panel).await?;
        }

        transaction.commit().await.map_err(unavailable)?;

        Ok(Layout {
            id,
            owner: new.owner,
            title: new.title,
            visibility: new.visibility,
            forked_from: new.forked_from,
            time_range: new.time_range,
            panels: new.panels,
            created_at: now,
            updated_at: now,
        })
    }

    async fn update_layout(&self, layout: &Layout) -> Result<()> {
        let now = Utc::now();
        let mut transaction = self.pool.begin().await.map_err(unavailable)?;

        let done = sqlx::query(
            "UPDATE layouts SET title = $2, visibility = $3, time_range = $4, updated_at = $5 \
             WHERE id = $1",
        )
        .bind(layout.id)
        .bind(&layout.title)
        .bind(layout.visibility.as_str())
        .bind(&layout.time_range)
        .bind(now)
        .execute(&mut *transaction)
        .await
        .map_err(unavailable)?;

        if done.rows_affected() == 0 {
            return Err(StoreError::NotFound {
                entity: "layout",
                id: layout.id.to_string(),
            });
        }

        // Panels are replaced wholesale. A layout is edited as one thing, and
        // reconciling individual panels would cost more than it saves on
        // surfaces this size.
        sqlx::query("DELETE FROM panel_instances WHERE layout_id = $1")
            .bind(layout.id)
            .execute(&mut *transaction)
            .await
            .map_err(unavailable)?;

        for panel in &layout.panels {
            insert_panel(&mut transaction, layout.id, panel).await?;
        }

        transaction.commit().await.map_err(unavailable)
    }

    async fn delete_layout(&self, id: Uuid) -> Result<bool> {
        // Panels go with it by cascade; forks survive with their provenance
        // cleared, by the ON DELETE SET NULL on the reference.
        let done = sqlx::query("DELETE FROM layouts WHERE id = $1")
            .bind(id)
            .execute(&self.pool)
            .await
            .map_err(unavailable)?;
        Ok(done.rows_affected() > 0)
    }

    async fn fork_layout(&self, id: Uuid, new_owner: &str) -> Result<Layout> {
        let original = self.layout(id).await?.ok_or_else(|| StoreError::NotFound {
            entity: "layout",
            id: id.to_string(),
        })?;

        self.create_layout(NewLayout {
            owner: new_owner.to_string(),
            title: original.title,
            visibility: Visibility::Personal,
            forked_from: Some(original.id),
            time_range: original.time_range,
            panels: original
                .panels
                .into_iter()
                .map(|panel| PanelInstance {
                    id: Uuid::new_v4(),
                    ..panel
                })
                .collect(),
        })
        .await
    }

    // -- Sessions ---------------------------------------------------------

    async fn begin_login(&self, pending: PendingLogin) -> Result<()> {
        sqlx::query(
            "INSERT INTO pending_logins (state, nonce, code_verifier, redirect_to, created_at, expires_at)
             VALUES ($1, $2, $3, $4, $5, $6)",
        )
        .bind(&pending.state)
        .bind(&pending.nonce)
        .bind(&pending.code_verifier)
        .bind(&pending.redirect_to)
        .bind(pending.created_at)
        .bind(pending.expires_at)
        .execute(&self.pool)
        .await
        .map_err(unavailable)?;
        Ok(())
    }

    async fn claim_login(&self, state: &str) -> Result<Option<PendingLogin>> {
        // Deleted and returned in one statement. Two would leave a window in
        // which a replayed callback arriving from elsewhere reads the same row
        // before the first request has removed it, which is the whole thing
        // single use is here to prevent.
        let row = sqlx::query(
            "DELETE FROM pending_logins WHERE state = $1
             RETURNING state, nonce, code_verifier, redirect_to, created_at, expires_at",
        )
        .bind(state)
        .fetch_optional(&self.pool)
        .await
        .map_err(unavailable)?;

        let Some(row) = row else {
            return Ok(None);
        };

        let pending = PendingLogin {
            state: row.get("state"),
            nonce: row.get("nonce"),
            code_verifier: row.get("code_verifier"),
            redirect_to: row.get("redirect_to"),
            created_at: row.get("created_at"),
            expires_at: row.get("expires_at"),
        };

        Ok(Some(pending).filter(|pending| Utc::now() < pending.expires_at))
    }

    async fn create_session(&self, session: Session) -> Result<()> {
        sqlx::query(
            "INSERT INTO sessions (id, subject, name, groups, created_at, expires_at)
             VALUES ($1, $2, $3, $4, $5, $6)",
        )
        .bind(&session.id)
        .bind(&session.subject)
        .bind(&session.name)
        .bind(serde_json::to_value(&session.groups).unwrap_or_default())
        .bind(session.created_at)
        .bind(session.expires_at)
        .execute(&self.pool)
        .await
        .map_err(unavailable)?;
        Ok(())
    }

    async fn session(&self, id: &str) -> Result<Option<Session>> {
        // Expiry is in the query as well as on the type: a sweeper that has not
        // run yet must never be the reason an expired session still works.
        let row = sqlx::query(
            "SELECT id, subject, name, groups, created_at, expires_at
             FROM sessions WHERE id = $1 AND expires_at > now()",
        )
        .bind(id)
        .fetch_optional(&self.pool)
        .await
        .map_err(unavailable)?;

        let Some(row) = row else {
            return Ok(None);
        };

        let groups: serde_json::Value = row.get("groups");
        let groups = serde_json::from_value(groups)
            .map_err(|error| StoreError::Corrupt(format!("session groups: {error}")))?;

        Ok(Some(Session {
            id: row.get("id"),
            subject: row.get("subject"),
            name: row.get("name"),
            groups,
            created_at: row.get("created_at"),
            expires_at: row.get("expires_at"),
        }))
    }

    async fn end_session(&self, id: &str) -> Result<bool> {
        let done = sqlx::query("DELETE FROM sessions WHERE id = $1")
            .bind(id)
            .execute(&self.pool)
            .await
            .map_err(unavailable)?;
        Ok(done.rows_affected() > 0)
    }

    async fn sweep_expired(&self) -> Result<u64> {
        let sessions = sqlx::query("DELETE FROM sessions WHERE expires_at <= now()")
            .execute(&self.pool)
            .await
            .map_err(unavailable)?;

        let logins = sqlx::query("DELETE FROM pending_logins WHERE expires_at <= now()")
            .execute(&self.pool)
            .await
            .map_err(unavailable)?;

        Ok(sessions.rows_affected() + logins.rows_affected())
    }
}

async fn insert_panel(
    transaction: &mut sqlx::Transaction<'_, sqlx::Postgres>,
    layout_id: Uuid,
    panel: &PanelInstance,
) -> Result<()> {
    sqlx::query(
        "INSERT INTO panel_instances (id, layout_id, platform_id, panel_key, kind_override, \
                                      title_override, selections, customizations, position, created_at)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)",
    )
    .bind(panel.id)
    .bind(layout_id)
    .bind(&panel.platform_id)
    .bind(&panel.panel_key)
    .bind(&panel.kind_override)
    .bind(&panel.title_override)
    .bind(&panel.selections)
    .bind(&panel.customizations)
    .bind(&panel.position)
    .bind(panel.created_at)
    .execute(&mut **transaction)
    .await
    .map_err(unavailable)?;
    Ok(())
}
